# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# AutoDUT CI Tool pipeline. For demo pipelines see 'gitlab' module
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Global pipeline rules (can be narrowed inside each job)
workflow:
  rules:
    #- if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_COMMIT_TAG'
    - if: '$CI_PIPELINE_SOURCE == "web"'
    #- if: '$CI_PIPELINE_SOURCE == "api"'

# Pipeline stages
stages:
  - build_docker_image

# Jobs

# Build and upload docker image
Build docker image:
  stage: build_docker_image
  script:
    # Define if an extra tag will be used (in case of git tag only)
    - export EXTRA_TAG=${CI_COMMIT_TAG:+"-t ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"};
    # Login to private registry
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY};
    # Build our image, avoiding all cache to ensure a full & fresh build
    - docker buildx build tools/docker ${EXTRA_TAG} -t ${CI_REGISTRY_IMAGE}:latest --no-cache --pull --platform linux/386;
    # Send a tagged image to registry (only when git tag)
    - if [ ! -z "${CI_COMMIT_TAG}" ]; then docker push ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}; fi
    # Send 'latest' to registry (always available)
    - docker push ${CI_REGISTRY_IMAGE}:latest;
  artifacts: {}
